[package]
name = "sqlx_bug_reproduce"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
sqlx = {version = "0.7.3", features = ["sqlite", "runtime-tokio"]}
tokio = {version = "1.36.0", features = ["rt-multi-thread", "macros"]}
